name: Build and Test Sh%opping App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout the repoistory
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies 
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display SoftUnit username
      run: echo "yanabg"
